INSERT INTO `activecalls`
(`id`, `server_id`, `uniqueid`,         `start_time`, `answer_time`, `transfer_time`, `src`,         `dst`,       `src_device_id`, `dst_device_id`, `channel`,                   `dstchannel`, `prefix`, `provider_id`, `did_id`, `user_id`, `owner_id`, `localized_dst`) VALUES
(26,    1,           '1249296552.111086',NOW(),        NOW(),          NULL,            '306984327342','63727007889', 12,              0,               'SIP/10.219.62.200-c40daf10','',           '63',     1,              0,       8,         0,          '63727007889');
  
INSERT INTO `calls` (`id`, `calldate`          , `clid`               , `src`       , `dst`       , `channel`, `duration`, `billsec`, `disposition`, `accountcode`, `uniqueid`   , `src_device_id`, `dst_device_id`, `processed`, `did_price`, `card_id`, `provider_id`, `provider_rate`, `provider_billsec`, `provider_price`, `user_id`, `user_rate`, `user_billsec`, `user_price`, `reseller_id`, `reseller_rate`, `reseller_billsec`, `reseller_price`, `partner_id`, `partner_rate`, `partner_billsec`, `partner_price`, `prefix`, `server_id`, `hangupcause`, `callertype`, `did_inc_price`, `did_prov_price`, `localized_dst`, `did_provider_id`, `did_id`, `originator_ip`, `terminator_ip`, `real_duration`, `real_billsec`, `did_billsec`)
VALUES (116  ,DATE_SUB(NOW(), INTERVAL 30 SECOND),''                    ,'101'        ,'8652'     ,''         ,40         ,50        ,'ANSWERED'    ,'2'           ,'12321133792.3',2               ,0               ,0           ,0           ,0         ,1             ,0               ,9                  ,1                ,8         ,1           ,1              ,8            ,3             ,0               ,0                  ,4                ,0            ,0              ,0                 ,0               ,'1231'   ,1           ,16            ,'Local'      ,0               ,0                ,'123123'        ,0                 ,0        ,''              ,''              ,0               ,0              ,0);

INSERT INTO `calls` (`id`, `calldate`          , `clid`               , `src`       , `dst`       , `channel`, `duration`, `billsec`, `disposition`, `accountcode`, `uniqueid`   , `src_device_id`, `dst_device_id`, `processed`, `did_price`, `card_id`, `provider_id`, `provider_rate`, `provider_billsec`, `provider_price`, `user_id`, `user_rate`, `user_billsec`, `user_price`, `reseller_id`, `reseller_rate`, `reseller_billsec`, `reseller_price`, `partner_id`, `partner_rate`, `partner_billsec`, `partner_price`, `prefix`, `server_id`, `hangupcause`, `callertype`, `did_inc_price`, `did_prov_price`, `localized_dst`, `did_provider_id`, `did_id`, `originator_ip`, `terminator_ip`, `real_duration`, `real_billsec`, `did_billsec`)
VALUES (107  ,DATE_SUB(NOW(), INTERVAL 30 SECOND),''                    ,'101'        ,'8652'     ,''         ,40         ,50        ,'ANSWERED'    ,'2'           ,'12321133792.3',2               ,0               ,0           ,0           ,0         ,1             ,0               ,9                  ,1                ,8         ,1           ,1              ,8            ,3             ,0               ,0                  ,4                ,0            ,0              ,0                 ,0               ,'1231'   ,1           ,16            ,'Local'      ,0               ,0                ,'123123'        ,0                 ,0        ,''              ,''              ,0               ,0              ,0);

INSERT INTO `cs_invoices` (`id`, `callshop_id`, `user_id`, `state`, `invoice_type`, `balance`, `comment`, `paid_at`, `updated_at`, `created_at`) VALUES (5, 4, 8, 'unpaid', 'prepaid', 8.00, 'komentar4444as', NULL, DATE_SUB(NOW() , INTERVAL 1 HOUR), DATE_SUB(NOW(), INTERVAL 1 HOUR));
